
[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Thomas Braibant <thomas.braibant@gmail.com>"]
edition = "2021"

[dependencies]
scan_fmt = "0.2.6"
chrono = "0.4"
prettytable-rs = "0.8"
nom = "7.1"